"""Interactive live-diagnostics chart: a candlestick chart of one market
with a click-to-inspect panel below it — clicking any candle shows the
full per-piece pass/fail trace (src.live.diagnostics.trace_entry_signal)
recorded for that bar's check, if one was ever run for it (a bar from
before the live container started, or a gap in fetched data, has no
trace — shown as "not evaluated", not treated as an error).

Regenerated by scripts/run_live_check_volatility.py after every check, so
opening (or just refreshing) the local HTML file always shows the latest
state. Deliberately a plain local file, not a published Artifact: an
unattended container has no way to write to an Artifact's live database
(only Claude, via the Artifact tool, can — see this project's own
dashboard, which hit the same limitation and stayed a static, manually
republished snapshot for exactly that reason). A local file the container
itself rewrites every hour has no such gap.
"""
from __future__ import annotations

import json
from pathlib import Path

import pandas as pd
import plotly.graph_objects as go


def render_live_diagnostics_chart(df: pd.DataFrame, diagnostics_by_timestamp: dict[str, dict], symbol: str) -> str:
    """`df`: OHLCV to plot (any window — the diagnostics dict only needs
    covering the bars actually checked so far). `diagnostics_by_timestamp`:
    `str(timestamp) -> trace_entry_signal(...)`-shaped dict (plus
    `signal`), as accumulated by scripts/run_live_check_volatility.py."""
    # x as plain strings (str(pd.Timestamp), not raw Timestamps): plotly's
    # own JSON serialization of a Timestamp column drops the timezone
    # offset and swaps the separator ("2026-09-15T14:00:00"), which would
    # never match diagnose_entry's own `str(timestamp)` keys
    # ("2026-09-15 14:00:00+00:00") in the click handler below — this
    # keeps ONE canonical string format on both sides instead of guessing
    # plotly's date formatting to reverse it in JS.
    x = df["timestamp"].astype(str)
    fig = go.Figure(
        data=[go.Candlestick(x=x, open=df["open"], high=df["high"], low=df["low"], close=df["close"], name=symbol)]
    )
    fig.update_layout(
        title=f"{symbol} — historial de evaluación en vivo",
        xaxis_rangeslider_visible=False,
        height=520,
        margin=dict(t=48, b=32),
    )

    chart_div = fig.to_html(include_plotlyjs="cdn", full_html=False, div_id="chart")
    diagnostics_json = json.dumps(diagnostics_by_timestamp)

    return f"""<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>{symbol} — live diagnostics</title>
<style>
  body {{ font-family: system-ui, -apple-system, sans-serif; margin: 0; padding: 20px; background: #0f1115; color: #e6e6e6; }}
  h1 {{ font-size: 1.3rem; margin: 0 0 4px; }}
  p.hint {{ color: #9aa0a6; margin: 0 0 16px; }}
  #panel {{ margin-top: 16px; padding: 16px; background: #1a1d24; border: 1px solid #2a2d35; border-radius: 8px; min-height: 100px; }}
  #panel h2 {{ margin: 0 0 12px; font-size: 1rem; font-weight: 600; }}
  .piece {{ display: flex; justify-content: space-between; padding: 6px 0; border-bottom: 1px solid #2a2d35; font-size: 0.92rem; }}
  .piece:last-child {{ border-bottom: none; }}
  .pass {{ color: #4caf50; font-weight: 600; }}
  .fail {{ color: #e53935; font-weight: 600; }}
  .final {{ font-weight: 700; margin-top: 8px; font-size: 1rem; }}
  em {{ color: #9aa0a6; }}
</style>
</head>
<body>
<h1>{symbol} — historial de evaluación en vivo</h1>
<p class="hint">Click en una vela para ver qué piezas de la estrategia pasaron o fallaron en ese cierre.</p>
{chart_div}
<div id="panel"><em>Click en una vela para ver el detalle.</em></div>
<script>
const diagnostics = {diagnostics_json};
const plotDiv = document.getElementById('chart');
function passFailLabel(passed) {{
  return passed ? '<span class="pass">PASA</span>' : '<span class="fail">FALLA</span>';
}}
plotDiv.on('plotly_click', function(data) {{
  const point = data.points[0];
  const ts = point.x;
  const panel = document.getElementById('panel');
  const trace = diagnostics[ts];
  if (!trace) {{
    panel.innerHTML = '<em>Sin evaluación registrada para esta vela (anterior al inicio del contenedor, o hueco de datos).</em>';
    return;
  }}
  let html = `<h2>${{ts}}</h2>`;
  html += `<div class="piece"><span>context (${{trace.context_value}}, requiere ${{trace.context_required}})</span>${{passFailLabel(trace.context_passed)}}</div>`;
  html += `<div class="piece"><span>setup</span>${{passFailLabel(trace.setup_passed)}}</div>`;
  trace.confirmations.forEach(function(c) {{
    html += `<div class="piece"><span>${{c.piece}}</span>${{passFailLabel(c.passed)}}</div>`;
  }});
  html += `<div class="piece final"><span>SEÑAL FINAL</span>${{trace.signal ? '<span class="pass">SÍ, ENTRA</span>' : '<span class="fail">NO</span>'}}</div>`;
  panel.innerHTML = html;
}});
</script>
</body>
</html>
"""


def write_live_diagnostics_chart(
    df: pd.DataFrame, diagnostics_by_timestamp: dict[str, dict], symbol: str, output_path: Path
) -> Path:
    html = render_live_diagnostics_chart(df, diagnostics_by_timestamp, symbol)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(html, encoding="utf-8")
    return output_path
